version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-live
    container_name: formula1charts-container
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=formula1charts.settings
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - ./static:/app/static
      - ./db.sqlite3:/app/db.sqlite3
    command: gunicorn formula1charts.wsgi:application --bind 0.0.0.0:8000

# docker-compose up -d --build